services:
  dice-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dice-app-dev
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
      - android-sdk-cache:/opt/android-sdk
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ANDROID_HOME=/opt/android-sdk
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /app
    command: bash

volumes:
  gradle-cache:
  android-sdk-cache: