name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true
        
    - name: Cache Kotlin/Native dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-konan-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Desktop tests
      run: ./gradlew :composeApp:desktopTest
      
    - name: Build Desktop application
      run: ./gradlew :composeApp:compileKotlinDesktop
      
    - name: Check Android compilation
      run: ./gradlew :composeApp:compileDebugKotlinAndroid
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          composeApp/build/reports/tests/
          composeApp/build/test-results/
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          composeApp/build/distributions/
          composeApp/build/libs/